/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h264_encoder_NativeH264Encoder */

#ifndef _Included_NativeH264Encoder
#define _Included_NativeH264Encoder
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Method:    InitEncoder
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h264_encoder_NativeH264Encoder_InitEncoder
  (JNIEnv *, jclass, jobject);

/*
 * Method:    Get NAL
 */
JNIEXPORT jbyteArray JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h264_encoder_NativeH264Encoder_getNAL
  (JNIEnv *env, jclass iclass);

/*
 * Method:    EncodeFrame
 */
JNIEXPORT jbyteArray JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h264_encoder_NativeH264Encoder_ResizeAndEncodeFrame
  (JNIEnv *, jclass, jbyteArray, jlong, jboolean, jint, jint);

/*
 * Method:    EncodeFrame
 */
JNIEXPORT jbyteArray JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h264_encoder_NativeH264Encoder_EncodeFrame
  (JNIEnv *, jclass, jbyteArray, jlong, jboolean, jfloat);

/*
 * Method:    DeinitEncoder
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h264_encoder_NativeH264Encoder_DeinitEncoder
  (JNIEnv *, jclass);

/*
 * Method:    GetLastEncodeStatus
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h264_encoder_NativeH264Encoder_getLastEncodeStatus
  (JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
